config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_dotdrop.fish:
    src: config/fish/functions/dotdrop.fish
    dst: ~/.config/fish/functions/dotdrop.fish
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  d_spacevim.d:
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
  d_i3:
    src: i3
    dst: ~/.i3
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_config:
    src: config/fcitx/config
    dst: ~/.config/fcitx/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_default.custom.yaml:
    src: config/fcitx/rime/default.custom.yaml
    dst: ~/.config/fcitx/rime/default.custom.yaml
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
  d_conky:
    src: xmonad/conky
    dst: ~/.xmonad/conky
  f_xmonad.hs:
    src: xmonad/xmonad.hs
    dst: ~/.xmonad/xmonad.hs
  f_taskrc:
    src: taskrc
    dst: ~/.taskrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zsh:
    src: zsh
    dst: ~/.zsh
profiles:
  mslxl-PC:
    dotfiles:
    - f_dotdrop.fish
    - f_xprofile
    - d_spacevim.d
    - d_i3
    - f_xresources
    - f_config
    - f_i3status_config
    - f_xmodmap
    - f_default.custom.yaml
    - f_mimeapps.list
    - f_alacritty.yml
    - d_alacritty
    - f_picom.conf
    - d_spacemacs.d
    - d_conky
    - f_xmonad.hs
    - f_taskrc
    - f_zshrc
    - d_zsh
