config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_dotdrop.fish:
    src: config/fish/functions/dotdrop.fish
    dst: ~/.config/fish/functions/dotdrop.fish
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  d_spacevim.d:
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
  d_i3:
    src: i3
    dst: ~/.i3
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_config:
    src: config/fcitx/config
    dst: ~/.config/fcitx/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_init.fish:
    src: config/omf/init.fish
    dst: ~/.config/omf/init.fish
  f_sakura.conf:
    src: config/sakura/sakura.conf
    dst: ~/.config/sakura/sakura.conf
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_compton.conf:
    src: config/compton.conf
    dst: ~/.config/compton.conf
  f_default.custom.yaml:
    src: config/fcitx/rime/default.custom.yaml
    dst: ~/.config/fcitx/rime/default.custom.yaml
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
profiles:
  mslxl-PC:
    dotfiles:
    - f_dotdrop.fish
    - f_xprofile
    - d_spacevim.d
    - d_i3
    - f_xresources
    - f_config
    - f_i3status_config
    - f_init.fish
    - f_sakura.conf
    - f_xmodmap
    - f_compton.conf
    - f_default.custom.yaml
    - f_mimeapps.list
